### ISSUE TITLE
Upload avatar button on Profile Page

### ISSUE THREAD

**Issue by dejanzivanov** [GQDeltex/ft_transcendence#143]
If the user does not upload default one must be set

**Comment by Yuerino** [comment]
#224

**Comment by Kromolux** [comment]
How can we go back to default without storing it?
Ether we store it in the database or we ask intra for the default picture.
Both ways needs a lot of changes.
We should open another issue for the default picture.

**Comment by GQDeltex** [comment]
Put that in BACKLOG then, this is not a required feature (as much as it makes sense to have it)
