### ISSUE TITLE
Game is running in background

### ISSUE THREAD

**Issue by GQDeltex** [GQDeltex/ft_transcendence#178]
The game keeps running in the background if you switch to a different page. Not only that. It still accepts key input while you, for example, type a channel name in the channel creation page. Fun, but probably not what we want ;-)

**Comment by belgishboy** [comment]
For me it doesn't. It saves that state of the game when I first click to another page. Both of my 'paddle' disappear though.

**Comment by c8p2d01** [comment]
i think this should come into being fixed while we implement the PLAY site itself and taking care of the loading and unloading of the component, which is currently used standalone in here

**Comment by GQDeltex** [comment]
> For me it doesn't. It saves that state of the game when I first click to another page. Both of my 'paddle' disappear though.

Funny. Because my paddles are still there. They move to the top of the playing field though... Weird

**Comment by GQDeltex** [comment]
Maybe this could help https://stackoverflow.com/a/65989529. Just check if the current Page is the "Play" page and pause/unload if you are not on that page
