### ISSUE TITLE
Cannot find docker-compose WSL2

### ISSUE THREAD

**Issue by GQDeltex** [GQDeltex/ft_transcendence#188]
On WSL2 on a fresh install of Docker (not Docker Desktop) the shell cannot find `docker-compose` it is `docker compose` instead. We should write a rule to check for both (somehow ask docker for support on `docker compose`) so we could fallback

**Comment by Yuerino** [comment]
My WSL2 works fine with our current makefile and I followed the installation guide from Docker, but I guess this may depends on machine?

**Comment by GQDeltex** [comment]
We had problems after the install following the official instructions on @Eduard-Hosu Machine

**Comment by Yuerino** [comment]
> We had problems after the install following the official instructions on @Eduard-Hosu Machine

We also have `docker compose` on school mac and apparently it's the newer version so we can just migrate to that

**Comment by GQDeltex** [comment]
But i don't have `docker compose` installed... So I'd like to keep the backwards compatibility

**Comment by GQDeltex** [comment]
Added fallback in #200
