### ISSUE TITLE
Update ban flag after ban time elapsed

### ISSUE THREAD

**Issue by Madasanya** [GQDeltex/ft_transcendence#251]
When the user is banned on the channel, the ban flag is set to true. After the ban time has elapsed, the flag must be updated to false for the component that displays the user in the correct section.

**Comment by Yuerino** [comment]
as we talk about, this might be [relevant](https://docs.nestjs.com/techniques/task-scheduling#dynamic-timeouts)

**Comment by belgishboy** [comment]
> as we talked about, this might be [relevant](https://docs.nestjs.com/techniques/task-scheduling#dynamic-timeouts)

Ya, I talked to the other group and they said that they had implemented it using setTimeout()
