### ISSUE TITLE
aboutMe dataDisplay

### ISSUE THREAD

**Issue by c8p2d01** [GQDeltex/ft_transcendence#253]
### Topic
display names and other data instead of the hardcoded stuff
### To Do
 - [x] User Name
 - [x] First Name
 - [x] Last Name
 - [x] Intra Login
 - [ ] Coalition (probably removed)
 - [ ] Last Login (not extract, build ourselves)
 - [x] Campus

**Comment by GQDeltex** [comment]
Coalition and Campus are not required (some of the others are also not required but we already have them anyways to it's fine).
I'd suggest taking the work that's done and closing the issue. We could add a backlog issue for coalition and last login
