### ISSUE TITLE
Game flow

### ISSUE THREAD

**Issue by GQDeltex** [GQDeltex/ft_transcendence#266]
```
join queue
-> subscriber: if two found, create game
create game
-> move both users from queue to game
-> send both users game start event
game data
-> broadcasted via room ('&game-id')
goal
-> update score in database
win
-> if game finished, set game status to "ended"
-> send both end event
```

**Comment by GQDeltex** [comment]
Thanks to @c8p2d01 for this nice chart:
![grafik](https://user-images.githubusercontent.com/14111831/197981316-f458fdb9-c4a2-48f8-88ca-9db244e1a3bb.png)

**Comment by c8p2d01** [comment]
may complete #145 though because that one has no description i am unsure where it was meant to apply an an issue
