### ISSUE TITLE
Fix Game Layout

### ISSUE THREAD

**Issue by c8p2d01** [GQDeltex/ft_transcendence#301]
add a minimum size, and a XYratio to the scaling
also maybe reposition the height of the playing field as for now the calculation is a bit janky

**Comment by c8p2d01** [comment]
also try and figure out how to add the original text-Font for the score

**Comment by hennneh** [comment]
found this for the font: https://www.mattlag.com/bitfonts/
the 5x3 seems to be the one we're looking for
