### ISSUE TITLE
Limit the number of chars for a password

### ISSUE THREAD

**Issue by Kromolux** [GQDeltex/ft_transcendence#419]

**Comment by GQDeltex** [comment]
From the official [npm bcrypt docs](https://www.npmjs.com/package/bcrypt):
> Per bcrypt implementation, only the first 72 bytes of a string are used. Any extra bytes are ignored when matching passwords. Note that this is not the first 72 characters. It is possible for a string to contain less than 72 characters, while taking up more than 72 bytes (e.g. a UTF-8 encoded string containing emojis).

Just make the max password length 72
