### ISSUE TITLE
401 Error Skin selection shop

### ISSUE THREAD

**Issue by GQDeltex** [GQDeltex/ft_transcendence#437]
**Describe the bug**
I get an error after I bought an Item in the Skin Selection Shop

**To Reproduce**
1. Go to 'Skin selection'
2. Buy 'Soccer Ball'
3. Fill PayPal Credentials

**Expected behavior**
Buy a thing and have it without getting an error.

**Screenshots**
<img width="2461" alt="Screen Shot 2022-11-02 at 2 55 24 PM" src="https://user-images.githubusercontent.com/14111831/199507939-0f58078d-bf20-4a30-a3d6-707dc63976ca.png">

**Browser Logs**
If applicable, add the logs from your browsers 'console' tab in the development console.

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Firefox

**Comment by Yuerino** [comment]
Was because of missing paypal secret from env
