### ISSUE TITLE
Navbar doesn't reappear after game

### ISSUE THREAD

**Issue by GQDeltex** [GQDeltex/ft_transcendence#439]
**Describe the bug**
The navbar should reappear if you e.g. go back with the back button in your browser

**To Reproduce**
1. Go to 'Play'
2. Play Game
3. Click the back button in your browser

**Expected behavior**
See the NavBar

**Screenshots**
<img width="2560" alt="Screen Shot 2022-11-02 at 3 04 04 PM" src="https://user-images.githubusercontent.com/14111831/199510137-52531629-4e9e-44ab-8afc-66e56177f391.png">

**Browser Logs**

**Desktop (please complete the following information):**
 - OS: MacOs
 - Browser: Firefox

**Additional context**

**Comment by belgishboy** [comment]
its if you do 'back' on any page
