### ISSUE TITLE
Chat username change

### ISSUE THREAD

**Issue by belgishboy** [GQDeltex/ft_transcendence#442]
**Describe the bug**
If you are in a one-on-one chat with someone who changes their name and you try to send a message to them, it cannot found the user.

**To Reproduce**
1. Start one-on-one with another user
2. other user changes username
3. send a message to other username.
4. See error entitie not found.

**Expected behavior**
Not have an error. Chat should maybe send to user ids?

**Desktop (please complete the following information):**

**Additional context**

**Comment by GQDeltex** [comment]
I fixed that Issue, but we still have to test if that leads to collisions if a chat and a person have the same id (which could lead to severe Problems)
