### ISSUE TITLE
Add `make re` to Makefile

### ISSUE THREAD

**Issue by GQDeltex** [GQDeltex/ft_transcendence#5]
Add a `make re` rule to the makefile

**Comment by Kromolux** [comment]
Hey @GQDeltex,
I have assigned myself to this issue.
What about adding some more features like, rule to remove docker images, docker prune and phony?

**Comment by GQDeltex** [comment]
Yes! This is a great idea.

**Comment by GQDeltex** [comment]
You could also add a rule for formatting and linting (see the Wiki Page for ESLint on how that works). Use the docker version for the Makefile.

**Comment by GQDeltex** [comment]
And after our meeting today. Also add rules for attaching directly to a shell in the backend and frontend containters
