### ISSUE TITLE
Login on frontend

### ISSUE THREAD

**Issue by Yuerino** [GQDeltex/ft_transcendence#55]
So now that we have login route on the backend, we want to integrate it somehow on the frontend as well

## Proposal flow:

- [x] On the frontend, we have a login page with a login button
- [x] This button redirects to <backend>/login
- [x] <backend>/login will redirect to intra 42 login page
- [x] After successfully authenticating there, 42 intra redirects back to <backend>/login/redirect
- [x] There, passport does its magic and backend receives user data.
- [x] Backend then generate a JWT Token, add user to DB and we use that to manage user session
- [x] We set JWT token to cookie and redirect back to <frontend>/home
- [x] On /home, it will first call /users/me to check if it logged in (with jwt cookie) and get back user data (page life cycle)
- [x] Frontend will store the user data and jwt token on local storage with [Vuex store](https://vuex.vuejs.org/)
- [x] So now frontend will know if user is logged in and we can create a [navigation guard](https://router.vuejs.org/guide/advanced/navigation-guards.html#global-before-guards) based on that, and if user isn't logged in, it will redirect to <frontend> login page
- [x] Frontend landing page will display user profile picture and username instead of the modified sexy guy placeholder one

**Comment by GQDeltex** [comment]
1. Do we need a whole Store Package (Vuex/Pinia) to store a string in local-storage? We could just use the builtin JS/TS bindings? What are the advantages?

2. Also why are we redirecting from /home to /users/me and then back after authentication? I think that's a bit much redirecting, we could just ask for the data on /home if we don't have it I guess

**Comment by Yuerino** [comment]
> 1. Do we need a whole Store Package (Vuex/Pinia) to store a string in local-storage? We could just use the builtin JS/TS bindings? What are the advantages?

As I understood, Vuex/Pinia is for managing state while local storage is for storage. With Vuex/Pinia, any component that use that data are able to be aware of the changes and react to it while. But the state would be gone if you refresh the page. Local storage is just storage. If you update local storage, other component that use that data in local storage won't be aware of the changes, there's trick to go around it but it will be extra work. So the 2 things are different so it depends on what we want to do.

> 2. Also why are we redirecting from /home to /users/me and then back after authentication? I think that's a bit much redirecting, we could just ask for the data on /home if we don't have it I guess

When we are redirected to <frontend>/home, we won't redirect back to <backend>/users/me, we just simply call that API endpoint to get back the user data

**Comment by GQDeltex** [comment]
As previously discussed:
1. Having a store makes sense because of the ease of use and reactivity.
2. For the `/users/me` endpoint I would just request my own data via my user-id which is stored in the jwt via the GraphQL API.
