### ISSUE TITLE
GraphQL Internal server error when query bad user ID

### ISSUE THREAD

**Issue by Yuerino** [GQDeltex/ft_transcendence#77]
### Problem
Backend GraphQL return internal server error when query non-existing user id, this should return bad request or user not found instead.

### Reproduce
```graphql
query User($id: Int!) {
  user(id: $id) {
    id
    username
    picture
  }
}
```
GraphQL variable 
```json
{
  "id": 69
}
```
Will return internal server error with error message `Cannot return null for non-nullable field Query.user.`

**Comment by GQDeltex** [comment]
Do we want to have an error in that case or just return null?

**Comment by GQDeltex** [comment]
We want to throw a `QueryFailedError` in the Service.
